name = "telegramify-markdown"
main = "src/worker.js"
workers_dev = true
preview_urls = false
compatibility_date = "2025-10-01"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true
head_sampling_rate = 1
